/**
 * Typed IPC API for the renderer process.
 *
 * All IPC calls go through this module, components and hooks import named functions from here
 * rather than calling window.api directly. The calls themselves live in `ipc/`, grouped by the
 * area of the app they serve.
 */

export {
  getAppVersion,
  getCorruptRecoveryEvents,
  getLifecyclePhase,
  getSystemStatus,
  getValidationErrors,
  openAudioPreviewWindow,
  openCueEditorWindow,
  openPath,
  retryControllerInit,
  showItemInFolder,
} from './ipc/appShell'

export {
  getActiveAudioMotionCue,
  getActiveRb3MotionCue,
  getActiveYargMotionCue,
  getAudioConfig,
  getAudioEnabled,
  getAudioGameMode,
  getAudioReactiveCues,
  getDisabledAudioCues,
  getDisabledAudioMotionCues,
  getDisabledRb3Cues,
  getDisabledRb3MotionCues,
  getDisabledYargCues,
  getDisabledYargMotionCues,
  getEnabledAudioCueGroups,
  getEnabledAudioMotionCueGroups,
  getEnabledRb3CueGroups,
  getEnabledRb3MotionCueGroups,
  getEnabledYargMotionCueGroups,
  getMotionEnabled,
  getRb3CueGroups,
  getRb3MotionCueGroups,
  saveAudioConfig,
  sendAudioData,
  setActiveAudioCue,
  setActiveAudioMotionCue,
  setActiveRb3MotionCue,
  setActiveYargMotionCue,
  setAudioEnabled,
  setAudioGameMode,
  setDisabledAudioCues,
  setDisabledAudioMotionCues,
  setDisabledRb3Cues,
  setDisabledRb3MotionCues,
  setDisabledYargCues,
  setDisabledYargMotionCues,
  setEnabledAudioCueGroups,
  setEnabledAudioMotionCueGroups,
  setEnabledRb3CueGroups,
  setEnabledRb3MotionCueGroups,
  setEnabledYargMotionCueGroups,
  setMotionEnabled,
} from './ipc/audio'

export {
  deleteDmxRig,
  exportRig,
  getActiveRigs,
  getDmxRig,
  getDmxRigs,
  getLightLayout,
  getLightLibrary,
  getMyLights,
  getPrefs,
  pickRigImportFile,
  saveDmxRig,
  saveLightLayout,
  saveMyLights,
  savePrefs,
} from './ipc/config'

export {
  deleteEffectFile,
  deleteNodeCueFile,
  exportEffectFile,
  exportNodeCueFile,
  getNodeCueTypes,
  listEffectFiles,
  listNodeCueFiles,
  pickEffectImportFile,
  pickNodeCueImportFile,
  readEffectFile,
  readNodeCueFile,
  reloadEffectFiles,
  reloadNodeCueFiles,
  saveEffectFile,
  saveNodeCueFile,
  setNodeCueDebug,
  validateEffect,
  validateNodeCue,
} from './ipc/cueAuthoring'

export {
  disableCueGroup,
  enableCueGroup,
  getAudioCueGroups,
  getAudioMotionCueGroups,
  getAudioMotionCueProbabilityPercent,
  getAudioMotionGroupSelectionMode,
  getAvailableAudioCues,
  getAvailableAudioMotionCues,
  getAvailableCues,
  getAvailableRb3Cues,
  getAvailableRb3MotionCues,
  getAvailableYargMotionCues,
  getConsistencyStatus,
  getCueConsistencyWindow,
  getCueGroupSelectionMode,
  getCueGroups,
  getCueSourceGroup,
  getEnabledCueGroups,
  getMotionCueMinHoldMs,
  getMotionCueProbabilityPercent,
  getRb3CueGroupSelectionMode,
  getRb3MotionCueDuration,
  getRb3MotionCueMinHoldMs,
  getRb3MotionCueProbabilityPercent,
  getRb3MotionGroupSelectionMode,
  getYargFallbackCueTimeMs,
  getYargMotionCueGroups,
  getYargMotionGroupSelectionMode,
  setAudioMotionCueProbabilityPercent,
  setAudioMotionGroupSelectionMode,
  setCueConsistencyWindow,
  setCueGroupSelectionMode,
  setEnabledCueGroups,
  setMotionCueMinHoldMs,
  setMotionCueProbabilityPercent,
  setRb3CueGroupSelectionMode,
  setRb3MotionCueDuration,
  setRb3MotionCueMinHoldMs,
  setRb3MotionCueProbabilityPercent,
  setRb3MotionGroupSelectionMode,
  setYargFallbackCueTimeMs,
  setYargMotionGroupSelectionMode,
  startAudioMotionCueSimulation,
  startRb3MotionCueSimulation,
  startYargMotionCueSimulation,
  stopMotionCueSimulation,
} from './ipc/cueSelection'

export {
  disableConsole,
  enableConsole,
  getClockRate,
  getMasterOutput,
  getRunningMotionCue,
  getStageKitPriority,
  sendConsoleDmx,
  setClockRate,
  setConsoleFixtureConfig,
  setMasterOutput,
  setStageKitPriority,
} from './ipc/lighting'

export {
  disableRb3,
  disableYarg,
  enableRb3,
  enableYarg,
  getRb3Enabled,
  getRb3Mode,
  getRb3Stats,
  getYargEnabled,
  setCueStyle,
  setListenCueData,
} from './ipc/listeners'

export {
  disableSender,
  enableSender,
  getNetworkInterfaces,
  updateArtNetConfig,
  updateEnttecConfig,
  updateSacnConfig,
} from './ipc/senders'

export {
  setRb3SimLedState,
  simulateBeat,
  simulateInstrumentNote,
  simulateKeyframe,
  simulateMeasure,
  simulatePostProcessing,
  startRb3TestEffect,
  startTestEffect,
  stopTestEffect,
} from './ipc/simulation'
